# This is needed to fetch private dependencies (e.g. `cggmp21`).
# This will make Cargo use the locally installed Git,
# and whatever SSH config you have to access Github.
[net]
git-fetch-with-cli=true
