name: Trigger Cloud Build

on:
  push:
    tags:
      - release/v[0-9]+.[0-9]+.[0-9]+-?**  # Release, or pre-release build.
      - release/v[0-9]+.[0-9]+.[0-9]+\+?** # Release with build identifier.
      # Then, also, basically any release-ish name in the `test/` tagspace.
      - test/**release/**
  schedule:
    # Build the default branch weekly. Our version of "nightly."
    - cron: 55 4 * * 0   # Every Sunday at 4:55 AM.

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 #v2.1.10
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a #v2.1.4

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit \
            --config=cloudbuild.yaml \
            --substitutions=_TAG_NAME=${{ github.ref_name }} \
            --repo=https://github.com/cooldracula/yocto-build \
            --branch=main \
            --project=${{ secrets.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
